import { Santri, Guru, Halaqah, Kelas, InstitutionSettings, UserProfile, AuditLog, UserRole, RolePermissions } from '../types';

export const INITIAL_SETTINGS: InstitutionSettings = {
  namaLembaga: 'Pondok Pesantren & Rumah Tahfidz Ar-Risalah',
  alamat: 'Jl. Raya Bukittinggi - Payakumbuh Km 7, Nagari Lasi, Kec. Canduang, Kab. Agam',
  prefixNis: 'ARR',
  tahunAjaranAktif: '2025/2026',
  nomorSuratHeader: '001/PP-ARR/VII/2026',
  email: 'info@arrisalah-lasi.sch.id',
  telepon: '+62 812-6789-9900',
  kota: 'Agam',
};

export const DEFAULT_ROLE_PERMISSIONS: Record<UserRole, RolePermissions> = {
  super_admin: {
    canManageSantri: true,
    canManageMasterData: true,
    canInputTahfidz: true,
    canInputAbsensi: true,
    canManageKeuangan: true,
    canManageSettings: true,
  },
  guru: {
    canManageSantri: false,
    canManageMasterData: false,
    canInputTahfidz: true,
    canInputAbsensi: true,
    canManageKeuangan: false,
    canManageSettings: false,
  },
  bendahara: {
    canManageSantri: false,
    canManageMasterData: false,
    canInputTahfidz: false,
    canInputAbsensi: false,
    canManageKeuangan: true,
    canManageSettings: false,
  },
  kepala_lembaga: {
    canManageSantri: true,
    canManageMasterData: true,
    canInputTahfidz: true,
    canInputAbsensi: true,
    canManageKeuangan: true,
    canManageSettings: true,
  },
  orang_tua: {
    canManageSantri: false,
    canManageMasterData: false,
    canInputTahfidz: false,
    canInputAbsensi: false,
    canManageKeuangan: false,
    canManageSettings: false,
  },
};

export const SAMPLE_USERS: UserProfile[] = [
  {
    uid: 'u-superadmin',
    email: 'superadmin@simsan.id',
    displayName: 'Ustadz Dr. H. Ahmad Syauqi, M.A.',
    role: 'super_admin',
    status: 'active',
    phone: '081234567890'
  },
  {
    uid: 'u-guru',
    email: 'guru@simsan.id',
    displayName: 'Ustadz Abdullah Al-Hafidz',
    role: 'guru',
    status: 'active',
    phone: '085211223344'
  },
  {
    uid: 'u-bendahara',
    email: 'bendahara@simsan.id',
    displayName: 'Ustadzah Fatimah, S.E.',
    role: 'bendahara',
    status: 'active',
    phone: '081377889900'
  },
  {
    uid: 'u-kepala',
    email: 'kepala@simsan.id',
    displayName: 'KH. Muhammad Ridwan, Lc.',
    role: 'kepala_lembaga',
    status: 'active',
    phone: '081122334455'
  },
  {
    uid: 'u-orangtua',
    email: 'orangtua@simsan.id',
    displayName: 'Bapak H. Zulkarnein',
    role: 'orang_tua',
    status: 'active',
    phone: '081299887766'
  }
];

export const SAMPLE_SANTRI: Santri[] = [
  {
    id: 'santri-1',
    nis: 'ARR-2026-000001',
    nik: '1306011504080001',
    noKK: '1306012010150045',
    nama: 'Muhammad Rayhan Al-Fatih',
    namaPanggilan: 'Rayhan',
    jenisKelamin: 'L',
    tempatLahir: 'Bukittinggi',
    tanggalLahir: '2008-04-15',
    alamat: 'Jalan Surau Gadang No. 12',
    jorong: 'Lasi Tuo',
    nagari: 'Lasi',
    kecamatan: 'Canduang',
    kabupaten: 'Agam',
    provinsi: 'Sumatera Barat',
    kodePos: '26192',
    status: 'Aktif',
    tanggalMasuk: '2024-07-10',
    asalSekolah: 'SMP IT Al-Islami',
    jenjang: 'Pondok Pesantren',
    kelas: 'X IPA 1',
    halaqah: 'Halaqah Al-Jazari',
    guruPembimbing: 'Ustadz Abdullah Al-Hafidz',
    catatan: 'Santri berprestasi hafalan 10 Juz',
    namaAyah: 'H. Zulkarnein',
    nikAyah: '1306011005750002',
    pendidikanAyah: 'S1 Teknik',
    pekerjaanAyah: 'Wiraswasta',
    hpAyah: '081299887766',
    namaIbu: 'Hj. Nurbaiti',
    nikIbu: '1306015508780003',
    pendidikanIbu: 'S1 Pendidikan',
    pekerjaanIbu: 'Guru PNS',
    hpIbu: '081366554433',
    qrCodeData: 'SIMSAN:ARR-2026-000001:Muhammad Rayhan Al-Fatih',
    createdAt: '2026-01-15T08:00:00.000Z',
    updatedAt: '2026-07-20T10:30:00.000Z'
  },
  {
    id: 'santri-2',
    nis: 'ARR-2026-000002',
    nik: '1306016208090002',
    noKK: '1306012010150089',
    nama: 'Aisyah Humaira Az-Zahra',
    namaPanggilan: 'Aisyah',
    jenisKelamin: 'P',
    tempatLahir: 'Payakumbuh',
    tanggalLahir: '2009-08-22',
    alamat: 'Jorong Pasanehan No. 45',
    jorong: 'Pasanehan',
    nagari: 'Lasi',
    kecamatan: 'Canduang',
    kabupaten: 'Agam',
    provinsi: 'Sumatera Barat',
    kodePos: '26192',
    status: 'Aktif',
    tanggalMasuk: '2024-07-10',
    asalSekolah: 'MTsN 1 Agam',
    jenjang: 'Rumah Tahfidz',
    kelas: 'Kelas Ula A',
    halaqah: 'Halaqah Khadijah',
    guruPembimbing: 'Ustadzah Siti Maryam',
    catatan: 'Aktif dalam kegiatan Bahasa Arab',
    namaAyah: 'Drs. Supriadi',
    hpAyah: '085233445566',
    namaIbu: 'Rina Marlina, S.Ag',
    hpIbu: '085277889900',
    qrCodeData: 'SIMSAN:ARR-2026-000002:Aisyah Humaira Az-Zahra',
    createdAt: '2026-01-16T09:00:00.000Z',
    updatedAt: '2026-07-18T14:20:00.000Z'
  },
  {
    id: 'santri-3',
    nis: 'ARR-2026-000003',
    nik: '1307011202100003',
    noKK: '1307011210150012',
    nama: 'Fathan Al-Ghazali',
    namaPanggilan: 'Fathan',
    jenisKelamin: 'L',
    tempatLahir: 'Padang Panjang',
    tanggalLahir: '2010-02-12',
    alamat: 'Jl. Ahmad Yani No. 8',
    jorong: 'Koto Tuo',
    nagari: 'Balai Gurah',
    kecamatan: 'IV Angkat',
    kabupaten: 'Agam',
    provinsi: 'Sumatera Barat',
    kodePos: '26191',
    status: 'Aktif',
    tanggalMasuk: '2025-07-12',
    asalSekolah: 'SDIT Cahaya Hati',
    jenjang: 'Madrasah Diniyah',
    kelas: 'Kelas Wustha 1',
    halaqah: 'Halaqah Al-Shatibi',
    guruPembimbing: 'Ustadz Hamzah',
    namaAyah: 'Ibrahim, S.E.',
    hpAyah: '081311223344',
    namaIbu: 'Salmawati',
    hpIbu: '081355667788',
    qrCodeData: 'SIMSAN:ARR-2026-000003:Fathan Al-Ghazali',
    createdAt: '2026-02-01T10:00:00.000Z',
    updatedAt: '2026-06-10T11:00:00.000Z'
  },
  {
    id: 'santri-4',
    nis: 'ARR-2026-000004',
    nik: '1306020511110004',
    noKK: '1306021210150077',
    nama: 'Zahra An-Nabila',
    namaPanggilan: 'Zahra',
    jenisKelamin: 'P',
    tempatLahir: 'Batusangkar',
    tanggalLahir: '2011-11-05',
    alamat: 'Jln. Sutan Syahrir No. 19',
    jorong: 'Lasi Mudo',
    nagari: 'Lasi',
    kecamatan: 'Canduang',
    kabupaten: 'Agam',
    provinsi: 'Sumatera Barat',
    kodePos: '26192',
    status: 'Aktif',
    tanggalMasuk: '2025-07-12',
    asalSekolah: 'MIN 2 Agam',
    jenjang: 'TPQ',
    kelas: 'TPA B',
    halaqah: 'Halaqah Aisyah',
    guruPembimbing: 'Ustadzah Nurul',
    namaAyah: 'Dedi Kurniawan',
    hpAyah: '082188990011',
    namaIbu: 'Yulia Fransiska',
    hpIbu: '082122334455',
    qrCodeData: 'SIMSAN:ARR-2026-000004:Zahra An-Nabila',
    createdAt: '2026-02-10T11:00:00.000Z',
    updatedAt: '2026-05-01T09:15:00.000Z'
  },
  {
    id: 'santri-5',
    nis: 'ARR-2025-000088',
    nik: '1306011001070005',
    noKK: '1306012010150011',
    nama: 'Ahmad Bilal Al-Bukhari',
    namaPanggilan: 'Bilal',
    jenisKelamin: 'L',
    tempatLahir: 'Padang',
    tanggalLahir: '2007-01-10',
    alamat: 'Koto Baru, Canduang',
    jorong: 'Koto Baru',
    nagari: 'Canduang Koto Laweh',
    kecamatan: 'Canduang',
    kabupaten: 'Agam',
    provinsi: 'Sumatera Barat',
    kodePos: '26192',
    status: 'Alumni',
    tanggalMasuk: '2022-07-15',
    asalSekolah: 'SMP 1 Canduang',
    jenjang: 'Pondok Pesantren',
    kelas: 'XII IPA',
    halaqah: 'Halaqah Al-Jazari',
    guruPembimbing: 'Ustadz Abdullah Al-Hafidz',
    catatan: 'Telah khatam 30 Juz Al-Qur\'an (Tahun 2025)',
    namaAyah: 'Drs. H. Mansyur',
    hpAyah: '081244556677',
    namaIbu: 'Hj. Syamsiah',
    hpIbu: '081288990011',
    qrCodeData: 'SIMSAN:ARR-2025-000088:Ahmad Bilal Al-Bukhari',
    createdAt: '2025-07-15T08:00:00.000Z',
    updatedAt: '2026-01-10T08:00:00.000Z'
  }
];

export const WILAYAH_DATA = {
  kecamatan: ['Canduang', 'IV Angkat', 'Banuhampu', 'Sungai Pua', 'Baso', 'Tilatang Kamang'],
  nagari: {
    'Canduang': ['Lasi', 'Canduang Koto Laweh', 'Bukik Batabuah'],
    'IV Angkat': ['Balai Gurah', 'Batu Taba', 'Ampang Gadang', 'Lambah', 'Panampuang'],
    'Banuhampu': ['Kubang Putiah', 'Caniago', 'Pulao Punjung'],
    'Sungai Pua': ['Sungai Pua', 'Batu Palano', 'Sariak'],
    'Baso': ['Simarasok', 'Tabek Panjang', 'Koto Tinggi'],
    'Tilatang Kamang': ['Koto Tangah', 'Capo Koto']
  },
  jorong: {
    'Lasi': ['Lasi Tuo', 'Lasi Mudo', 'Pasanehan'],
    'Canduang Koto Laweh': ['Koto Baru', 'Gantiang', 'Bingkudu'],
    'Bukik Batabuah': ['Kubang Duo', 'Batu Taba'],
    'Balai Gurah': ['Koto Tuo', 'Sitalang', 'Sitiung'],
    'Batu Taba': ['Batu Taba Indah', 'Kampung Tengah']
  }
};

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    userId: 'u-admin',
    userName: 'Ustadzah Rahmawati, S.Pd.',
    role: 'super_admin',
    action: 'Penerbitan NIS Santri Baru',
    target: 'ARR-2026-000004 (Zahra An-Nabila)',
    timestamp: '2026-07-22T19:30:00.000Z',
    details: 'Penambahan data santri baru jenjang TPQ dengan NIS otomatis'
  },
  {
    id: 'log-2',
    userId: 'u-superadmin',
    userName: 'Ustadz Dr. H. Ahmad Syauqi, M.A.',
    role: 'super_admin',
    action: 'Pembaruan Pengaturan Lembaga',
    target: 'Prefix NIS (ARR)',
    timestamp: '2026-07-21T14:15:00.000Z',
    details: 'Pembaruan header nomor surat dan prefix NIS lembaga'
  }
];
